DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS compilations_events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS locations;

CREATE TABLE IF NOT EXISTS categories (
  category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL UNIQUE,

  CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(256) NOT NULL UNIQUE,
  name VARCHAR(256) NOT NULL,

  CONSTRAINT pk_user PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS locations (
  location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lat FLOAT NOT NULL,
  lon FLOAT NOT NULL,

  CONSTRAINT pk_location PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT NOT NULL,
  description VARCHAR(7000) NOT NULL,
  event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  created_on TIMESTAMP WITHOUT TIME ZONE,
  published_on TIMESTAMP WITHOUT TIME ZONE,
  location_id BIGINT NOT NULL,
  paid BOOLEAN NOT NULL,
  participant_limit INTEGER,
  request_moderation BOOLEAN,
  user_id INTEGER NOT NULL,
  title VARCHAR(2000) NOT NULL,
  state VARCHAR(50),

  CONSTRAINT pk_event PRIMARY KEY (event_id),
  CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories ON DELETE CASCADE,
  CONSTRAINT fk_event_location FOREIGN KEY (location_id) REFERENCES locations ON DELETE CASCADE,
  CONSTRAINT fk_event_initiator FOREIGN KEY (user_id) REFERENCES users ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations (
  compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pinned BOOLEAN,
  title VARCHAR(50) NOT NULL,

  CONSTRAINT uq_title UNIQUE (title),
  CONSTRAINT pk_compilation PRIMARY KEY (compilation_id)
);

CREATE TABLE IF NOT EXISTS compilations_events (
  compilation_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  compilation_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,

  CONSTRAINT pk_comps_events PRIMARY KEY (compilation_event_id),
  CONSTRAINT uq_comps_events UNIQUE (compilation_id, event_id),
  CONSTRAINT fk_compilation_of_events FOREIGN KEY (compilation_id) REFERENCES compilations ON DELETE CASCADE,
  CONSTRAINT fk_event_from_compilation FOREIGN KEY (event_id) REFERENCES events ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
  request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE,
  event_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  status VARCHAR(50),

  CONSTRAINT pk_request PRIMARY KEY (request_id),
  CONSTRAINT uq_request UNIQUE (event_id, user_id),
  CONSTRAINT fk_event_request FOREIGN KEY (event_id) REFERENCES events ON DELETE CASCADE,
  CONSTRAINT fk_event_requester FOREIGN KEY (user_id) REFERENCES users ON DELETE CASCADE
);